#!/bin/sh
#
# Firefox shell script:
# optimize SQLite by using vacuum.
#
# Credit: http://ubuntuforums.org/showthread.php?t=1193567
#
# Firefox stores a lot of data, for example bookmarks, in database files.
# The files are in your profile directory and have the extension .sqlite.
#
# This script looks for sqlite database files in your `~/.mozilla` folder,
# then executes the sqlite vacuum command, which removes stale data.
#
# Command: firefox-optimize-sqlite-vacuum
# Version: 1.1.0
# Created: 2010-05-20
# Updated: 2015-01-25
# License: GPL
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
unameOut="$(uname -s)"
firefoxRoot=$HOME/.mozilla/

case "${unameOut}" in
    Linux*)     firefoxRoot=$HOME/.mozilla/;;
    Darwin*)    firefoxRoot=$HOME/Library/Application\ Support/Firefox/Profiles;;
    CYGWIN*)    firefoxRoot=$HOME/.mozilla/;;
    MINGW*)     firefoxRoot=$HOME/.mozilla/;;
    *)          firefoxRoot=$HOME/.mozilla/
esac
killall firefox
set -euf
echo "$firefoxRoot"
find "$firefoxRoot" \( -name "*.sqlite" \) -print -exec sqlite3 {} "vacuum" \;
